#!/usr/bin/env python3
# Authors: Dr. Denys Dutykh (Mathematics Department, Khalifa University of Science
# and Technology, Abu Dhabi, UAE) and Prof. Laurent Vuillon (Univ. Savoie Mont
# Blanc, CNRS, LAMA, Chambery, France).
# Copyright (C) 2026 Dr. Denys Dutykh and Prof. Laurent Vuillon.
# Distributed under the GNU Lesser General Public License, version 2.1;
# see the LICENSE file of this package.
"""Write the TikZ code of the three figures of the article from exact data.

``figures/cusp-cylinders.tex``: the cusp coordinate at the empty directive, with
the two rays of the orbit set, the poles of the first-letter maps, their four
distances to the rays and the two cylinders, with the columns of all words of
length at most nine.

``figures/twin-ladders.tex``: every palindrome with label at most ``10^12`` in
the plane of the ratio rho/M and the label; central words, twins joined by the rungs of their
block exchanges, and the centres of those exchanges.

``figures/nested-square.tex``: the first square of nested exchanges, at the label
12 986 074 130, with the rung below it and the midpoints of its two diagonals.

All arithmetic is exact (integers and fractions); coordinates are rounded to
three decimals of a centimetre only when written.  Run from the article folder:

    python3 -B supplement/code/make_figures.py
"""

import math
import sys
from collections import defaultdict
from fractions import Fraction
from pathlib import Path

if not __debug__:
    raise SystemExit("Run without -O.")

ROOT = Path(__file__).resolve().parents[2]
HEADER = ("% Author: Dr. Denys Dutykh (Khalifa University of Science and Technology, Abu Dhabi, UAE)\n"
          "% Generated by supplement/code/make_figures.py from exact data; do not edit by hand.\n")


def fmt(value):
    return f"{value:.3f}".rstrip("0").rstrip(".") if abs(value) >= 5e-4 else "0"


# ---------------------------------------------------------------------------
# Figure 1: the cusp coordinate at the empty directive.

def cusp_figure():
    scale = 1.98                       # centimetres per unit of z
    zmin, zmax = -3.95, 3.05

    def x(z):
        return (float(z) - zmin) * scale

    def f(z):                          # letter a: f(z) = -3 - 1/z
        return Fraction(-3) if z is None else -3 - 1 / z

    def g(z):                          # letter b: g(z) = 5/2 - 1/(4z + 2)
        return Fraction(5, 2) if z is None else Fraction(5, 2) - 1 / (4 * z + 2)

    points = {None}
    frontier = {None}
    for _ in range(9):
        frontier = {f(z) for z in frontier} | {g(z) for z in frontier}
        points |= frontier
    finite = sorted(z for z in points if z is not None)
    ticks = sorted({round(x(z), 3) for z in finite})

    u_box = (Fraction(-41, 12), Fraction(-3) + Fraction(12, 25))
    v_box = (Fraction(5, 2) - Fraction(10, 111), Fraction(21, 8))
    assert all(u_box[0] <= z <= u_box[1] or v_box[0] <= z <= v_box[1] for z in finite)

    lines = [HEADER, r"\begin{tikzpicture}[font=\footnotesize, >={Stealth[length=4pt]}]"]
    y_f, y_g = -0.78, -1.42
    # guides from the ends of the rays down to the distance arrows
    for z in (Fraction(-5, 2), Fraction(12, 5)):
        lines.append(rf"\draw[mist, densely dotted, line width=0.5pt] ({fmt(x(z))},-0.56) -- ({fmt(x(z))},{y_g - 0.12});")
    # the axis: gap thin, rays thick, both ends towards the point at infinity
    lines.append(rf"\draw[mist, line width=0.8pt] ({fmt(x(Fraction(-5, 2)))},0) -- ({fmt(x(Fraction(12, 5)))},0);")
    lines.append(rf"\draw[navy, line width=2.2pt] ({fmt(x(Fraction(-5, 2)))},0) -- ({fmt(x(zmin) + 0.15)},0);")
    lines.append(rf"\draw[navy, line width=2.2pt] ({fmt(x(Fraction(12, 5)))},0) -- ({fmt(x(zmax) - 0.15)},0);")
    lines.append(rf"\draw[navy, ->, line width=0.8pt] ({fmt(x(zmin) + 0.2)},0) -- ({fmt(x(zmin) - 0.05)},0);")
    lines.append(rf"\draw[navy, ->, line width=0.8pt] ({fmt(x(zmax) - 0.2)},0) -- ({fmt(x(zmax) + 0.05)},0);")
    lines.append(rf"\node[ink, below] at ({fmt(x(zmin))},-0.08) {{$\infty$}};")
    lines.append(rf"\node[ink, below] at ({fmt(x(zmax))},-0.08) {{$\infty$}};")
    lines.append(rf"\node[ink, below] at ({fmt(x(Fraction(-5, 2)))},-0.08) {{$-5/2$}};")
    lines.append(rf"\node[ink, below] at ({fmt(x(Fraction(12, 5)))},-0.08) {{$12/5$}};")
    lines.append(rf"\node[ink, below] at ({fmt(x(0))},-0.08) {{$0$}};")
    lines.append(rf"\draw[ink, line width=0.5pt] ({fmt(x(0))},-0.07) -- ({fmt(x(0))},0.07);")
    # the cylinders and the orbit points
    for (lo, hi), name in ((u_box, r"\mathcal U"), (v_box, r"\mathcal V")):
        lines.append(rf"\filldraw[fill=sand, draw=ink, line width=0.4pt] ({fmt(x(lo))},0.16) rectangle ({fmt(x(hi))},0.58);")
        lines.append(rf"\node[ink, above] at ({fmt((x(lo) + x(hi)) / 2)},0.6) {{${name}$}};")
    for t in ticks:
        lines.append(rf"\draw[navy, line width=0.25pt] ({fmt(t)},0.2) -- ({fmt(t)},0.54);")
    # the ranges of the poles and the four distances
    rows = (
        (y_f, Fraction(-5, 12), Fraction(0), "wine", r"pole of $f$", "25/12", "12/5"),
        (y_g, Fraction(-1, 2), Fraction(-3, 8), "teal", r"pole of $g$", "2", "111/40"),
    )
    for y, lo, hi, colour, name, left, right in rows:
        lines.append(rf"\draw[{colour}, <->, line width=0.6pt] ({fmt(x(-Fraction(5, 2)))},{y}) -- ({fmt(x(lo))},{y});")
        lines.append(rf"\draw[{colour}, <->, line width=0.6pt] ({fmt(x(hi))},{y}) -- ({fmt(x(Fraction(12, 5)))},{y});")
        lines.append(rf"\draw[{colour}, line width=3pt] ({fmt(x(lo))},{y}) -- ({fmt(x(hi))},{y});")
        lines.append(rf"\node[{colour}, above] at ({fmt((x(-Fraction(5, 2)) + x(lo)) / 2)},{y}) {{${left}$}};")
        lines.append(rf"\node[{colour}, above] at ({fmt((x(hi) + x(Fraction(12, 5))) / 2)},{y}) {{${right}$}};")
        lines.append(rf"\node[{colour}, below] at ({fmt((x(lo) + x(hi)) / 2)},{y - 0.04}) {{{name}}};")
    lines.append(r"\end{tikzpicture}")
    return "\n".join(lines) + "\n", len(finite)


# ---------------------------------------------------------------------------
# Figure 2: twins and ladders.

EXCHANGE = {"ab": "ba", "ba": "ab"}


def label_root(word):
    a11, a12, a21, a22 = 1, 0, 0, 1
    for letter in word:
        if letter == "a":
            a11, a12, a21, a22 = 2 * a11 + a12, a11 + a12, 2 * a21 + a22, a21 + a22
        else:
            a11, a12, a21, a22 = 5 * a11 + 2 * a12, 2 * a11 + a12, 5 * a21 + 2 * a22, 2 * a21 + a22
    x, y = 2 * a11 + a12, 2 * a21 + a22
    return 2 * x + y, x


def palindromes(bound):
    stack = [("", 2, 1)]
    while stack:
        w, x, y = stack.pop()
        even = x * x + y * y
        if even > bound:
            continue
        rw = w[::-1]
        for label, z in ((even, rw + w), (2 * x * x + 2 * x * y + y * y, rw + "a" + w),
                         (5 * x * x + 4 * x * y + y * y, rw + "b" + w)):
            if label <= bound:
                yield z
        stack.append(("a" + w, 2 * x + y, x + y))
        stack.append(("b" + w, 5 * x + 2 * y, 2 * x + y))


def pal(directive):
    """Iterated right palindromic closure, from the definition."""
    word = ""
    for letter in directive:
        word += letter
        for i in range(len(word) + 1):
            if word[i:] == word[i:][::-1]:
                word += word[:i][::-1]
                break
    return word


def central_words(bound):
    """All central words Pal(d) with label at most bound.

    Pal(d) is a proper prefix of Pal(dc), and a proper extension has a strictly
    larger label, so the search over directives can stop at the bound.
    """
    found, stack = set(), [""]
    while stack:
        d = stack.pop()
        z = pal(d)
        if label_root(z)[0] > bound:
            continue
        found.add(z)
        stack.extend((d + "a", d + "b"))
    return found


def exchange_partners(z):
    for length in range(len(z) - 1):
        p = z[:length]
        if p != p[::-1]:
            continue
        i, blocks = len(p), []
        while i < len(z):
            block = z[i:i + 2]
            if block not in EXCHANGE:
                break
            blocks.append(block)
            i += 2
            if z[i:i + len(p)] != p:
                break
            i += len(p)
        else:
            if len(blocks) >= 2:
                yield p, p + "".join(EXCHANGE[b] + p for b in blocks)


def ladder_figure(bound=10**12):
    words = list(palindromes(bound))
    data = {}
    by_label = defaultdict(list)
    for z in words:
        m, r = label_root(z)
        data[z] = (m, Fraction(r, m))
        by_label[m].append(z)
    rungs, feet = set(), set()
    for m, group in by_label.items():
        if len(group) < 2:
            continue
        for z in group:
            for p, partner in exchange_partners(z):
                assert partner in group
                rungs.add((m, tuple(sorted((z, partner))), p))
                feet.add(p)
    twins = {z for m, g in by_label.items() if len(g) > 1 for z in g}
    central = central_words(bound)
    assert central <= set(words)
    assert not (twins & central)

    smin, smax = (3 - math.sqrt(5)) / 2, math.sqrt(2) - 1
    width, height = 12.4, 7.0
    ymin, ymax = 0.5, 12.25

    def px(s):
        return (float(s) - smin) / (smax - smin) * width

    def py(m):
        return (math.log10(m) - ymin) / (ymax - ymin) * height

    out = [HEADER, r"\begin{tikzpicture}[font=\footnotesize]"]
    # frame: left and bottom spines, ticks outward
    out.append(rf"\draw[ink, line width=0.5pt] (0,{fmt(height)}) -- (0,0) -- ({fmt(width)},0);")
    for e in range(0, 13, 3):
        y = py(10 ** e) if e > 0 else py(1) if ymin <= 0 else None
        if y is None or y < 0:
            continue
        out.append(rf"\draw[ink, line width=0.5pt] (0,{fmt(y)}) -- (-0.08,{fmt(y)});")
        out.append(rf"\node[ink, left] at (-0.08,{fmt(y)}) {{$10^{{{e}}}$}};")
    for s in (0.385, 0.39, 0.395, 0.4, 0.405, 0.41):
        out.append(rf"\draw[ink, line width=0.5pt] ({fmt(px(s))},0) -- ({fmt(px(s))},-0.08);")
        out.append(rf"\node[ink, below] at ({fmt(px(s))},-0.08) {{${s:.3f}$}};")
    out.append(rf"\node[ink, below] at ({fmt(width / 2)},-0.48) {{$\rho(z)/M(z)$, the frequency of $b$ in $\Omega_z$}};")
    out.append(rf"\node[ink, rotate=90, above] at (-0.75,{fmt(height / 2)}) {{Gram label $M(z)$}};")
    # other palindromes, then central words
    for z in words:
        if z in twins or z in central:
            continue
        m, s = data[z]
        out.append(rf"\fill[slate] ({fmt(px(s))},{fmt(py(m))}) circle (0.28pt);")
    for z in sorted(central):
        m, s = data[z]
        out.append(rf"\fill[navy] ({fmt(px(s))},{fmt(py(m))}) circle (0.75pt);")
    # posts and rungs
    for m, (z1, z2), p in sorted(rungs):
        mp, sp = data[p] if p in data else label_root(p)
        out.append(rf"\draw[slate, densely dotted, line width=0.35pt] ({fmt(px(sp))},{fmt(py(mp))}) -- ({fmt(px(sp))},{fmt(py(m))});")
    for m, (z1, z2), p in sorted(rungs):
        s1, s2 = data[z1][1], data[z2][1]
        out.append(rf"\draw[wine, line width=0.7pt] ({fmt(px(s1))},{fmt(py(m))}) -- ({fmt(px(s2))},{fmt(py(m))});")
    for z in sorted(twins):
        m, s = data[z]
        out.append(rf"\draw[wine, fill=white, line width=0.45pt] ({fmt(px(s))},{fmt(py(m))}) circle (1.1pt);")
    for p in sorted(feet):
        m, s = data[p]
        out.append(rf"\filldraw[ochre, draw=ink, line width=0.25pt] ({fmt(px(s))},{fmt(py(m))}) +(0,1.9pt) -- +(1.9pt,0) -- +(0,-1.9pt) -- +(-1.9pt,0) -- cycle;")
        if p in twins:
            # a twin that is also a centre: ring the diamond so that both roles show
            out.append(rf"\draw[wine, line width=0.45pt] ({fmt(px(s))},{fmt(py(m))}) circle (2.7pt);")
    # labels of the three lowest centres, in empty space beside their diamonds
    for word, name, side in (("", r"$\varepsilon$", "right"), ("a", r"$a$", "right"), ("b", r"$b$", "left")):
        m, s = data[word]
        out.append(rf"\node[ink, {side}=2.2pt] at ({fmt(px(s))},{fmt(py(m))}) {{{name}}};")
    # legend above the plot, outside the data
    ly = height + 0.42
    out.append(rf"\fill[navy] (0.2,{fmt(ly)}) circle (0.75pt); \node[ink, right] at (0.28,{fmt(ly)}) {{central word}};")
    out.append(rf"\filldraw[ochre, draw=ink, line width=0.25pt] (2.6,{fmt(ly)}) +(0,1.9pt) -- +(1.9pt,0) -- +(0,-1.9pt) -- +(-1.9pt,0) -- cycle; \node[ink, right] at (2.7,{fmt(ly)}) {{centre $p$}};")
    out.append(rf"\draw[wine, line width=0.7pt] (4.5,{fmt(ly)}) -- (5.1,{fmt(ly)}); \draw[wine, fill=white, line width=0.45pt] (4.5,{fmt(ly)}) circle (1.1pt) (5.1,{fmt(ly)}) circle (1.1pt); \node[ink, right] at (5.2,{fmt(ly)}) {{twins and their rung}};")
    out.append(rf"\fill[slate] (8.85,{fmt(ly)}) circle (0.5pt); \node[ink, right] at (8.93,{fmt(ly)}) {{other palindrome}};")
    out.append(r"\end{tikzpicture}")
    stats = dict(palindromes=len(words), central=len(central), twins=len(twins),
                 rungs=len(rungs), feet=sorted(feet, key=lambda p: data[p][0]))
    return "\n".join(out) + "\n", stats


# ---------------------------------------------------------------------------
# Figure 3: the first square of nested exchanges.

def nested_square_figure():
    """The square of Corollary cor:nested-square for p empty and W = V = (ba, ab).

    The two lower levels are drawn to scale in the ratio rho/M.  At the top level each
    twin sits at a centre ratio plus or minus 3/N, N = 9*1130^2 + 1; these offsets are
    about 2.6e-7 and are drawn as a fixed visible distance, the same for every offset,
    so that the drawing keeps the exact geometry of the reflections.
    """
    def angle(q, blocks):
        return q + "".join(b + q for b in blocks)

    w = ["ba", "ab"]
    p1, p2 = angle("", w), angle("", [EXCHANGE[b] for b in w])
    z = [angle(p1, w), angle(p1, [EXCHANGE[b] for b in w]),
         angle(p2, w), angle(p2, [EXCHANGE[b] for b in w])]
    assert (p1, p2) == ("baab", "abba")
    assert z == ["baabbabaababbaab", "baababbaabbabaab", "abbabaabbaababba", "abbaababbabaabba"]
    m0, r0 = label_root("")
    m1, r1 = label_root(p1)
    m2, r2 = label_root(p2)
    data = [label_root(x) for x in z]
    m = data[0][0]
    n = 9 * m1 * m1 + 1
    assert (m0, r0, m1, r1, m2, r2) == (5, 2, 1130, 467, 1130, 437)
    assert all(d[0] == m for d in data) and m == m1 * n == 12986074130 and n == 11492101
    rho = [d[1] for d in data]
    assert rho == [r1 * n + 3 * m1, r1 * n - 3 * m1, r2 * n + 3 * m1, r2 * n - 3 * m1]
    c0, c1, c2 = Fraction(r0, m0), Fraction(r1, m1), Fraction(r2, m2)
    assert c1 + c2 == 2 * c0
    shift = Fraction(3, n)
    assert Fraction(rho[0] + rho[2], 2 * m) == c0 + shift and Fraction(rho[1] + rho[3], 2 * m) == c0 - shift
    assert Fraction(rho[0] + rho[1], 2 * m) == c1 and Fraction(rho[2] + rho[3], 2 * m) == c2
    assert Fraction(rho[0] + rho[3], 2 * m) == c0 and Fraction(rho[1] + rho[2], 2 * m) == c0

    smin, smax, width = 0.380, 0.420, 10.8
    d = 0.55                                    # drawn length of one offset 3/N

    def px(s):
        return (float(s) - smin) / (smax - smin) * width

    y0, y1, y2 = 0.55, 2.35, 4.75
    x0, x1, x2 = px(c0), px(c1), px(c2)
    top = {1: x1 + d, 2: x1 - d, 3: x2 + d, 4: x2 - d}   # Z_1..Z_4, sign of the offset as in rho
    assert abs((top[1] + top[4]) / 2 - x0) < 1e-9 and abs((top[2] + top[3]) / 2 - x0) < 1e-9

    def diamond(x, y, ringed=False):
        s = rf"\filldraw[ochre, draw=ink, line width=0.25pt] ({fmt(x)},{fmt(y)}) +(0,1.9pt) -- +(1.9pt,0) -- +(0,-1.9pt) -- +(-1.9pt,0) -- cycle;"
        if ringed:
            s += rf" \draw[wine, line width=0.45pt] ({fmt(x)},{fmt(y)}) circle (2.7pt);"
        return s

    out = [HEADER, r"\begin{tikzpicture}[font=\footnotesize]"]
    # ratio axis, to scale for the two lower levels
    out.append(rf"\draw[ink, line width=0.5pt] (0,0) -- ({fmt(width)},0);")
    for s in (0.385, 0.39, 0.395, 0.4, 0.405, 0.41, 0.415):
        out.append(rf"\draw[ink, line width=0.5pt] ({fmt(px(s))},0) -- ({fmt(px(s))},-0.08);")
        out.append(rf"\node[ink, below] at ({fmt(px(s))},-0.08) {{${s:.3f}$}};")
    out.append(rf"\node[ink, below] at ({fmt(width / 2)},-0.48) {{$\rho/M$}};")
    # level labels, left of the data
    for y, text in ((y0, r"$M=5$"), (y1, r"$M=1130$"), (y2, r"$M=12\,986\,074\,130$")):
        out.append(rf"\node[ink, left] at (-0.1,{fmt(y)}) {{{text}}};")
    # posts: the centre of every rung above its centre
    out.append(rf"\draw[slate, densely dotted, line width=0.4pt] ({fmt(x0)},{fmt(y0)}) -- ({fmt(x0)},{fmt(y2)});")
    out.append(rf"\draw[slate, densely dotted, line width=0.4pt] ({fmt(x1)},{fmt(y1)}) -- ({fmt(x1)},{fmt(y2)});")
    out.append(rf"\draw[slate, densely dotted, line width=0.4pt] ({fmt(x2)},{fmt(y1)}) -- ({fmt(x2)},{fmt(y2)});")
    # the lower rung, abba -- baab, around the empty word
    out.append(rf"\draw[navy, line width=0.8pt] ({fmt(x2)},{fmt(y1)}) -- ({fmt(x1)},{fmt(y1)});")
    # the exchanges around the empty word at the top level: two nested arcs above the row
    for (i, j), h in (((2, 3), 0.75), ((1, 4), 1.15)):
        a, b = top[j], top[i]
        out.append(rf"\draw[navy, line width=0.8pt] ({fmt(a)},{fmt(y2)}) .. controls ({fmt(a)},{fmt(y2 + h)}) and ({fmt(b)},{fmt(y2 + h)}) .. ({fmt(b)},{fmt(y2)});")
    # the short rungs, around baab and abba
    out.append(rf"\draw[wine, line width=0.9pt] ({fmt(top[2])},{fmt(y2)}) -- ({fmt(top[1])},{fmt(y2)});")
    out.append(rf"\draw[wine, line width=0.9pt] ({fmt(top[4])},{fmt(y2)}) -- ({fmt(top[3])},{fmt(y2)});")
    # the midpoints of the two diagonals, just below the row
    for x in (x0 - d, x0 + d):
        out.append(rf"\draw[ochre, fill=white, line width=0.6pt] ({fmt(x)},{fmt(y2 - 0.32)}) circle (1.5pt);")
    # annotation between the two upper levels, left of the centre post and right of the abba post
    tx, ty, tw = x2 + 0.32, (y1 + y2) / 2 - 0.12, 2.85
    assert x2 + 0.25 < tx and tx + tw < x0 - 0.15
    out.append(rf"\draw[slate, line width=0.35pt] ({fmt(x0 - d - 0.05)},{fmt(y2 - 0.38)}) -- ({fmt(tx + tw - 0.55)},{fmt(ty + 0.7)});")
    out.append(rf"\node[ink, right, align=left, inner sep=1pt] at ({fmt(tx)},{fmt(ty)}) {{midpoints $2/5\pm3/N$\\of the diagonals\\$(Z_1,Z_3)$ and $(Z_2,Z_4)$}};")
    # the four twins and their names
    for k, x in sorted(top.items()):
        out.append(rf"\draw[wine, fill=white, line width=0.45pt] ({fmt(x)},{fmt(y2)}) circle (1.3pt);")
        out.append(rf"\node[ink, below] at ({fmt(x)},{fmt(y2 - 0.06)}) {{$Z_{k}$}};")
    # the centres
    out.append(diamond(x0, y0))
    out.append(rf"\node[ink, right=2.2pt] at ({fmt(x0)},{fmt(y0)}) {{$\varepsilon$}};")
    out.append(diamond(x1, y1, ringed=True))
    out.append(rf"\node[ink, below right=1pt] at ({fmt(x1)},{fmt(y1)}) {{$baab$}};")
    out.append(diamond(x2, y1, ringed=True))
    out.append(rf"\node[ink, below left=1pt] at ({fmt(x2)},{fmt(y1)}) {{$abba$}};")
    # legend above the data, two rows
    la, lb = y2 + 2.05, y2 + 1.6
    out.append(rf"\draw[navy, line width=0.8pt] (0.2,{fmt(la)}) -- (0.8,{fmt(la)}); \node[ink, right] at (0.85,{fmt(la)}) {{exchange around $\varepsilon$}};")
    out.append(rf"\draw[wine, line width=0.9pt] (4.6,{fmt(la)}) -- (5.2,{fmt(la)}); \node[ink, right] at (5.25,{fmt(la)}) {{exchange around $baab$ or $abba$}};")
    out.append(diamond(0.5, lb) + rf" \node[ink, right] at (0.85,{fmt(lb)}) {{centre of an exchange}};")
    out.append(rf"\draw[ochre, fill=white, line width=0.6pt] (4.9,{fmt(lb)}) circle (1.5pt); \node[ink, right] at (5.25,{fmt(lb)}) {{midpoint of a diagonal}};")
    out.append(r"\end{tikzpicture}")
    return "\n".join(out) + "\n", dict(label=m, n=n)


def main():
    if len(sys.argv) != 1:
        raise SystemExit("This fixed generator accepts no arguments.")
    text, count = cusp_figure()
    (ROOT / "figures" / "cusp-cylinders.tex").write_text(text)
    print(f"figures/cusp-cylinders.tex: {count} orbit points of words of length at most nine")
    text, stats = ladder_figure()
    (ROOT / "figures" / "twin-ladders.tex").write_text(text)
    print(f"figures/twin-ladders.tex: {stats['palindromes']} palindromes, {stats['central']} central,"
          f" {stats['twins']} twins, {stats['rungs']} rungs, centres {stats['feet']}")
    text, info = nested_square_figure()
    (ROOT / "figures" / "nested-square.tex").write_text(text)
    print(f"figures/nested-square.tex: the square at label {info['label']}, N = {info['n']}")


if __name__ == "__main__":
    main()
